package erpglobals.modelglobals.globalsvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 23 15:51:25 PKT 2019
// ---------------------------------------------------------------------
public interface SysUsersVORow extends Row {
    void doERPChangePassword();
}

