package erpglobals.modelglobals.globalsqvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 24 14:44:32 PKT 2020
// ---------------------------------------------------------------------
public interface ERPDualTableForDepartmentQVORow extends Row {
    void ERPdoInsertAccessDepartment();
}

