package erpglobals.modelglobals.globalsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 03 11:30:33 PKT 2020
// ---------------------------------------------------------------------
public interface ErpUserCompanyAccessQVO extends ViewObject {
    void ErpdoInsertAccessableCompany();
}

