package erpglobals.modelglobals.globalsqvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 22 17:20:21 PKT 2019
// ---------------------------------------------------------------------
public interface ErpUserPolicyInformationQVORow extends Row {
    void doChangeERPPassword();
}

