package erpglobals.modelglobals.globalsqvo;

import erpglobals.modelglobals.globalsqvo.common.ErpUserPolicyInformationQVORow;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 22 17:18:36 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ErpUserPolicyInformationQVORowImpl extends ViewRowImpl implements ErpUserPolicyInformationQVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PasswordParameterSno,
        PasswordParameterName,
        PasswordParameterValue,
        MessageOnValidation,
        UserCode,
        txtNewPassword,
        txtConfirmPassword,
        txtStrength;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PASSWORDPARAMETERSNO = AttributesEnum.PasswordParameterSno.index();
    public static final int PASSWORDPARAMETERNAME = AttributesEnum.PasswordParameterName.index();
    public static final int PASSWORDPARAMETERVALUE = AttributesEnum.PasswordParameterValue.index();
    public static final int MESSAGEONVALIDATION = AttributesEnum.MessageOnValidation.index();
    public static final int USERCODE = AttributesEnum.UserCode.index();
    public static final int TXTNEWPASSWORD = AttributesEnum.txtNewPassword.index();
    public static final int TXTCONFIRMPASSWORD = AttributesEnum.txtConfirmPassword.index();
    public static final int TXTSTRENGTH = AttributesEnum.txtStrength.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ErpUserPolicyInformationQVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PasswordParameterSno.
     * @return the PasswordParameterSno
     */
    public Integer getPasswordParameterSno() {
        return (Integer) getAttributeInternal(PASSWORDPARAMETERSNO);
    }

    /**
     * Gets the attribute value for the calculated attribute PasswordParameterName.
     * @return the PasswordParameterName
     */
    public String getPasswordParameterName() {
        return (String) getAttributeInternal(PASSWORDPARAMETERNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute PasswordParameterValue.
     * @return the PasswordParameterValue
     */
    public String getPasswordParameterValue() {
        return (String) getAttributeInternal(PASSWORDPARAMETERVALUE);
    }

    /**
     * Gets the attribute value for the calculated attribute MessageOnValidation.
     * @return the MessageOnValidation
     */
    public String getMessageOnValidation() {
        return (String) getAttributeInternal(MESSAGEONVALIDATION);
    }

    /**
     * Gets the attribute value for the calculated attribute UserCode.
     * @return the UserCode
     */
    public String getUserCode() {
        return (String) getAttributeInternal(USERCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute txtNewPassword.
     * @return the txtNewPassword
     */
    public String gettxtNewPassword() {
        return (String) getAttributeInternal(TXTNEWPASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtNewPassword.
     * @param value value to set the  txtNewPassword
     */
    public void settxtNewPassword(String value) {
        setAttributeInternal(TXTNEWPASSWORD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtConfirmPassword.
     * @return the txtConfirmPassword
     */
    public String gettxtConfirmPassword() {
        return (String) getAttributeInternal(TXTCONFIRMPASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtConfirmPassword.
     * @param value value to set the  txtConfirmPassword
     */
    public void settxtConfirmPassword(String value) {
        setAttributeInternal(TXTCONFIRMPASSWORD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtStrength.
     * @return the txtStrength
     */
    public Integer gettxtStrength() {
        return (Integer) getAttributeInternal(TXTSTRENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtStrength.
     * @param value value to set the  txtStrength
     */
    public void settxtStrength(Integer value) {
        setAttributeInternal(TXTSTRENGTH, value);
    }

    public void doChangeERPPassword() {
        
        System.out.println("i am chainging password");
        System.out.println(gettxtNewPassword());
        System.out.println(gettxtConfirmPassword());
        settxtStrength(Integer.parseInt(gettxtNewPassword()));
        
    }
}

