package erpglobals.modelglobals.globalsqvo;

import erpglobals.modelglobals.ERPGlobalPLSQLClass;
import erpglobals.modelglobals.globalsqvo.common.ErpUserCompanyAccessQVO;

import java.sql.CallableStatement;
import java.sql.Timestamp;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 31 10:34:45 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ErpUserCompanyAccessQVOImpl extends ViewObjectImpl implements ErpUserCompanyAccessQVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ErpUserCompanyAccessQVOImpl() {
    }

    /**
     * Returns the bind variable value for P_ADF_USERID.
     * @return bind variable value for P_ADF_USERID
     */
    public Integer getP_ADF_USERID() {
        return (Integer) getNamedWhereClauseParam("P_ADF_USERID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_USERID.
     * @param value value to bind as P_ADF_USERID
     */
    public void setP_ADF_USERID(Integer value) {
        setNamedWhereClauseParam("P_ADF_USERID", value);
    }

    /**
     * Returns the bind variable value for P_ADF_MODULE_ACTION.
     * @return bind variable value for P_ADF_MODULE_ACTION
     */
    public String getP_ADF_MODULE_ACTION() {
        return (String) getNamedWhereClauseParam("P_ADF_MODULE_ACTION");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_MODULE_ACTION.
     * @param value value to bind as P_ADF_MODULE_ACTION
     */
    public void setP_ADF_MODULE_ACTION(String value) {
        setNamedWhereClauseParam("P_ADF_MODULE_ACTION", value);
    }

    /**
     * Returns the bind variable value for P_ADF_CURRENT_DATE.
     * @return bind variable value for P_ADF_CURRENT_DATE
     */
    public Timestamp getP_ADF_CURRENT_DATE() {
        return (Timestamp) getNamedWhereClauseParam("P_ADF_CURRENT_DATE");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_CURRENT_DATE.
     * @param value value to bind as P_ADF_CURRENT_DATE
     */
    public void setP_ADF_CURRENT_DATE(Timestamp value) {
        setNamedWhereClauseParam("P_ADF_CURRENT_DATE", value);
    }
    public void ErpdoInsertAccessableCompany() {
    System.out.println("ErpdoInsertAccessableCompany-V9");        
//    this.executeQuery();
    System.out.println("ErpdoInsertAccessableCompany-V10");
//     RowSetIterator rsi=this.getRowSetIterator();
     
//     String ERPTableName=ERPGlobalPLSQLClass.doGetERPModelTempCompAccessTable();
     
     String ErpTransType= ERPGlobalPLSQLClass.doErpGetConnTypeModel(getDBTransaction());
      if (ErpTransType.equals("ERPORACLE")) {
//           ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),"begin delete from  temp_admin_company_access; end;", "Y");  
//             ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),"begin proc_set_user_location_access(p_user_id ,p_module_action ,); end;", "N");  
            ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),"begin proc_set_user_location_access("+erpglobals.modelglobals.ERPGlobalPLSQLClass.doGetModelUserSno()+",'"+erpglobals.modelglobals.ERPGlobalPLSQLClass.doGetErpModuleAction()+"',"+erpglobals.modelglobals.ERPGlobalPLSQLClass.doGetModelGlobalDefCompany()+"); end;", "Y"); 
          
      }
       else {
//          CallableStatement cs = getDBTransaction().createCallableStatement("call new_procedure(1)", 1); 
            ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),"call proc_set_user_location_access("+erpglobals.modelglobals.ERPGlobalPLSQLClass.doGetModelUserSno()+",'"+erpglobals.modelglobals.ERPGlobalPLSQLClass.doGetErpModuleAction()+"',"+erpglobals.modelglobals.ERPGlobalPLSQLClass.doGetModelGlobalDefCompany()+")", "N");  
          
//          ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),"DROP temporary TABLE IF EXISTS temp_admin_company_access", "N");  
//          ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),"CREATE temporary TABLE temp_admin_company_access (\n" + 
//          "  company_id int(10) ,\n" + 
//          "  user_id int(10) ,\n" + 
//          "  global_company_id int(10) ,\n" + 
//          "  company_type_sno int(5) ,\n" + 
//          "  query_no int(2) ,\n" + 
//          "  parent_comp_code int(10) ,\n" + 
//          "  company_hierarchy_path varchar(200) ,\n" +
//          "  type_hierarchy_path varchar(200) ,\n" +
//          "  module_action varchar(10) ,\n" + 
//          "  created_by int(5) ,\n" + 
//          "  created_date datetime \n" + 
//          ") ", "N");
      }
       
     String ErpPlsql="";
//        rsi.reset();
//        rsi.setRangeSize(-1);
//        while (rsi.hasNext()) {
//            Row r=rsi.next();
//           ErpPlsql =
//                "insert into "+ERPTableName +
//                " (company_id,user_id,global_company_id,company_type_sno,query_no,parent_comp_code,company_hierarchy_path,type_hierarchy_path,module_action,created_by,created_date)" +
//                "values (" + 
//                r.getAttribute("CompCode") +","+
//                ERPGlobalPLSQLClass.doGetModelUserSno()+","+
//                r.getAttribute("GlobalCompCode")+","+
//                r.getAttribute("CompanyTypeSno")+","+
//                r.getAttribute("QueryNo")+","+
//                r.getAttribute("ParentCompCode")+","+
//                "'"+r.getAttribute("CompanyHierarchyPath")+"',"+
//                "'"+r.getAttribute("TypeHierarchyPath")+"',"+
//                "'"+ERPGlobalPLSQLClass.doGetErpModuleAction()+"',"+
//                ERPGlobalPLSQLClass.doGetModelUserSno();
//           if (ErpTransType.equals("ERPORACLE")) {
//               System.out.println("ErpPlsql+"+ErpPlsql);
//              // System.out.println("begin "+ ErpPlsql+",sysdate); end;");
//               ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),"begin "+ ErpPlsql+",sysdate); end;", "Y");  
//           }
//            else {
//               System.out.println(">>ErpPlsql+"+ErpPlsql);
//              // System.out.println("my-sql-calling");
//               ERPGlobalPLSQLClass.doErpExecutePLSQLModel(getDBTransaction(),ErpPlsql+",sysdate());", "Y");  
//               
//           }
//        }
    }
    
}

