package erpglobals.modelglobals.globalsvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 03 23:33:14 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TempAdminCompanyAccessVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TempAdminCompanyAccessVOImpl() {
    }
}

